[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["game", "LLM"]

[project]
name = "ai-textadventure"
version = "0.0.1"
dependencies = [
    "requests",
]